### ISSUE TITLE
Startlight Engine - Solve screen missing constraints

### ISSUE THREAD

**Issue by VaclavLustek** [Supernova-Studio/public-issue-tracker#1]
### Issue
> 	When using "Solve screen" to generate constraints, the resulting layout doesn't have all the necessary constraints and the layout is ambiguous when exported. 

### Current result
> 	There are usually a few vertical constraints missing when solving semi-complex layouts.

**Comment by JiriTrecak** [comment]
We will need to add a post-solve validation of the layout

**Comment by JiriTrecak** [comment]
Added to internal tracker [Supernova-Studio/supernova-studio-osx#161]
Expect the fix in the next release. Thank you.
