### ISSUE TITLE
[react native] styles are broken when exported

### ISSUE THREAD

**Issue by wasa4587** [Supernova-Studio/public-issue-tracker#100]
### Issue
The screen looks good in supernova studio, but when I export the project and run it, the styles are broken

### Context
Context
Supernova V6.2
Mac Mojave 10.14.3

### Expected result
​The screen looks the same

### Current result
The screen styles are broken when is exported to react native

### Screenshots
	
<img width="381" alt="Screen Shot 2019-03-19 at 7 18 52 AM" src="https://user-images.githubusercontent.com/2035706/54619535-5d8b4180-4a2a-11e9-8fd5-831148c12376.png">
<img width="406" alt="Screen Shot 2019-03-19 at 7 20 48 AM" src="https://user-images.githubusercontent.com/2035706/54619542-5fed9b80-4a2a-11e9-9701-1e87d5c3acb5.png">

**Comment by artufimtcev** [comment]
Fixed in 6.5
