### ISSUE TITLE
Add quotation marks to labels with < characters

### ISSUE THREAD

**Issue by maxtheman** [Supernova-Studio/public-issue-tracker#101]
### Issue
> 	Including the "<" character in your design will cause expo to fail when compiling

### Context
> 	I created a label with text saying "< back". This caused expo to throw an error.

### Expected result
> 	​Labels should be in "" so as to not interfere with the running!

**Comment by maxtheman** [comment]
Interestingly I was still having trouble compiling even with the character in "". I removed the character entirely to fix the issue.

**Comment by jan-supernova** [comment]
Hey maxtheman!
     We would like to inform you that the React Native issue with "<" ">" characters and characters in quotation marks had been fixed in the latest V7.1 version of Supernova Studio both for Basic and Expo project bases.

Have a wonderful day!  
Jan, Supernova Team
