### ISSUE TITLE
SuperNova hangs on import Sketch file

### ISSUE THREAD

**Issue by tdesc** [Supernova-Studio/public-issue-tracker#103]
### Issue
v6.3 (build 5160)

### Context
SuperNova hangs on import Sketch file

https://www.sketchappsources.com/free-source/3823-airport-app-concept-sketch-freebie-resource.html

### Expected result
SuperNova import file 

### Current result
SuperNova not responding

**Comment by jan-supernova** [comment]
Dear tsdec,
     We have tried to import the sketch file you have linked to Supernova V6.10 (build 5940) and import is working correctly. Try to update your Supernova Studio to the newest version.
