### ISSUE TITLE
Supernova Studio's history of Tab Bars gets desynced/broken after deleting a Tab Bar.

### ISSUE THREAD

**Issue by potatopotaro** [Supernova-Studio/public-issue-tracker#104]
### Issue
Supernova Studio's history of Tab Bars gets desynced/broken after deleting a Tab Bar.

### Context
I was investigating how Studio handles Tab Bars, and deleted my first Tab Bar. I then tried to create a new Tab Bar from one of the Tab Bar Screens.

### Expected result
I expected a new Tab Bar to be created.

### Current result
The option to create a Tab Bar is there (at the Screen), however clicking the options did nothing. The response was silent.

### Possible fix
**I am** able to create a Tab Group from the Navigation tab in Studio. Here's the interesting part:

1. If I have zero Tab Groups, and I create a Tab Group, it'll be called Tab Group #1.
2. If I delete Tab Group #1, and create a Tab Group again, of course, it'll be called Tab Group #1.
3. **However**, if I hover over the "Connect to an existing Tab Group" option from a Screen, I see a Tab Group with a number greater than 1 (if I followed steps 1 & 2 above).

I'm in slack and I can hop on a screenshare call if it would help.

**Comment by jan-supernova** [comment]
Dear potatopotaro,
      Thank you for your very detailed report. We have been able to successfully reproduce both of the issues that you have described. Our developers will look at those issues and we will let you know when they are fixed. Have a wonderful day!

Kind Regards,
     Jan Poisl

**Comment by jan-supernova** [comment]
Hey potatopotaro!  
We would like to inform you that this issue had been fixed in the newest version of the Supernova Studio. History of Tab Bars is no longer desynced in Supernova Studio V7.

Have a wonderful day!  
Jan, Supernova Team
