### ISSUE TITLE
Exporting multiple Flat Lists on the same screen, to React-Native, only exports one Flat List for that screen.

### ISSUE THREAD

**Issue by potatopotaro** [Supernova-Studio/public-issue-tracker#105]
### Issue
Exporting multiple Flat Lists on the same screen, to React-Native, only exports one Flat List for that screen.

### Context
I had 2 Flat Lists on a screen in Supernova Studio, and exported to React-Native.

### Expected result
All the Flat Lists would be there.

### Current result
Only one Flat List is allowed per screen.

**Comment by jan-supernova** [comment]
Hey potatopotaro,
     Thank you for your report! This issue is fixed in Supernova Studio V7.0, which will be released very soon. We have tried to simulate the issue in V7.0 by creating a screen with multiple Flat Lists and then by exporting the project to the React-Native (and checking out both Basic and Expo project builds). Multiple Flat Lists on one screen were exported properly and worked properly as well. We will let you know when the V7.0 is out!

Have a wonderful day!  
Jan, Supernova Team
