### ISSUE TITLE
Table View shows double the number of Table Cells (in the iOS simulator)

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#109]
### Issue
Table View Cells are duplicated when deployed to the iOS simulator

### Context
I have a Table View which contains three Table Cells.

### Expected result
When deploying to the iOS simulator I should see the same number of Table Cells that I have in my design. (the same number of cells that are shown in Supernova's Preview).

### Current result
The simulator shows _double the number of Table Cells_ ; instead of three cells, the simulator shows six.

### Possible fix
n/a

### Screenshots
Tricky to screenshot but here's a video:

[Duplicate_Table_Cells.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3068196/Duplicate_Table_Cells.mp4.zip)

**Comment by jan-supernova** [comment]
Hey steveharman,
We have tried to use different number of mock cells in Table View Cells in the simulator and it appears to be working correctly now. The simulator respects the set amount of mock cells in the Table View Cell. If the issue still persists for you, please, let us know.

Have a wonderful day!  
Jan, Supernova Team
