### ISSUE TITLE
Animation 'Repeat Count' property being ignored?

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#111]
### Observed in Supernova version
v6.7 & v7 Beta

### Issue
I have created a "spinning wheel" animation which I want to have repeated **three** times on tap.  It is only being repeated once. 

### Context

- Create an animation within Supernova.  
- Edit the animation's "Repeat Count" property to be a number greater than 1
- Enter Preview mode and invoke the animation

### Current result
Whatever "Repeat Count" property I specify I only ever get a single play of my animation

### Expected result
The animation should repeat/loop the number of times specified in the "Repeat Count" property. 

### Possible fix
n/a

### Screenshots
[tutleSpinsOnce.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3198432/tutleSpinsOnce.mp4.zip)

**Comment by jan-supernova** [comment]
Hey steveharman,
We are happy to inform you that *Repeat Count* property works properly now in the latest version V7.7 of Supernova Studio. It is working properly in Preview within Supernova Studio and is properly exported to Android and iOS platforms as well. Thank you again for reporting this issue!

Have a wonderful day!  
Jan, Supernova Team
