### ISSUE TITLE
No Launch / Splash screen displayed on iOS exports

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#112]
### Issue
The supplied launch image isn't used when deploying an iOS app to the simulator.

### Context
I have supplied all the required app icons and launch images at the specified dimensions for iOS and exported my project for iOS

### Current result
When launched in the simulator, the app successfully displays the **app icon** I supplied but instead of showing the **launch image** it simply shows a solid black screen.
 
### Expected result
Should display the launch image provided in Supernova's "Platform Images" feature

### Possible fix
n/a

### Screenshots
[viktoryLaunch720.mov.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3198649/viktoryLaunch720.mov.zip)

**Comment by steveharman** [comment]
Thanks to some great feedback from @JiriTrecak on Slack I was able to manually add the required launch images via XCode` [project] > Resources > Images > Images.xcassets`

If it helps with debugging this issue, it seems that Studio is creating image files for use as launch images in iOS - however, they're transparent/empty:

![Images_and_Images_xcassets](https://user-images.githubusercontent.com/12557929/58475325-8e33d980-8145-11e9-8141-b250ebfb645d.png)

**Comment by jan-supernova** [comment]
Hey steveharman,
We are pleased to inform you that the issue with no Launch/Splash screens displayed on iOS exports has been fixed in the latest version V7.7 of Supernova Studio which was just released and is available for download. Thank you again for reporting this issue!

Have a wonderful day!  
Jan, Supernova Team
