### ISSUE TITLE
com.supernova.project.Production value in exported iOS code despite setting our own ID

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#114]
### Issue
We see `com.supernova.project.Production` as the `PRODUCT_BUNDLE_IDENTIFIER` in the exported iOS project, when the `Bundle Identifier` parameter is set to be our own ID in Supernova's export settings

### Observed in Supernova version
6.7 & 7.0 Beta 1

### Context
Exporting as iOS from Supernova Studio

### Expected result
All references to the bundle ID should be the one specified in Supernova's export settings?

### Current result
A mixture of our bundle ID that's specified in the export settings and `com.supernova.project.Production` 

### Possible fix
Manually edit the .plist values in XCode

### Screenshots
Supernova export settings (showing our Bundle ID)
![bundleID1](https://user-images.githubusercontent.com/12557929/58472846-16fb4700-813f-11e9-8a61-1b3df186f69e.png)

XCode 10 showing `com.supernova.project.Production` as the `PRODUCT_BUNDLE_IDENTIFIER`
![bundleID2](https://user-images.githubusercontent.com/12557929/58472891-32fee880-813f-11e9-8e28-b8b3b5e49f79.png)

XCode 10 showing our bundle ID on the General tab
![bundleID3](https://user-images.githubusercontent.com/12557929/58472926-4ad66c80-813f-11e9-85cb-7fa421da5b92.png)

**Comment by jan-supernova** [comment]
Hey steveharman,
We are happy to inform you that custom IDs are now properly exported to the iOS platform in the latest version V7.7 of Supernova Studio which was released today and is available to download. Thank you again for reporting this issue!

Have a wonderful day!  
Jan, Supernova Team
