### ISSUE TITLE
Using an existing Navigation Bar component fails to preserve interaction parameters

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#115]
### Issue
When adding an existing Navigation Bar to another screen the interaction parameters are not applied to the newly created component.

### Observed in Supernova version
7.0 Beta 1

### Context

- I created my first Navigation Bar component on "screen 1" and configured the back-icon to have the 'Interaction Type' of "'Navigate Back'".  This works fine.
- I now want to use the same Navigation Bar component on other **identical** screens so I would go into screen 2, 3 and 4 where I also want to have Navigation Bars.
- Case:  edit screen 2, select the navigation bar elements on the screen and right-click > Convert to Navigation Bar > Use existing design > [choose the Navigation Bar component that I created previously]
- This applies the Navigation Bar but there is no Interaction Type of "Navigate Back" applied to the Navigation Bar that I create.

### Expected result
As I have created an Interaction Type of "Navigate Back" on the first Navigation Bar and subsequently applied the Navigation Bar design to other screens, as a user I would expect the same interaction parameters to be present as they were on the initial Navigation Bar.

### Current result
No Interaction Type of "Navigate Back" is applied to Navigation Bars when they are selected via Convert to Navigation Bar > Use existing design > [choose existing Navigation Bar component]
  
### Possible fix
Manually edit all Navigation Bars to assign them an interaction type & behavior.

### Screenshots
**Screen 1 -** the initial Navigation Bar 
![screen1](https://user-images.githubusercontent.com/12557929/58484299-b3cade00-8159-11e9-9907-bc46af348d94.png)

**Screen 2** - the Navigation Bars created with ` Convert to Navigation Bar > Use existing design`

![screen2](https://user-images.githubusercontent.com/12557929/58484460-03110e80-815a-11e9-86eb-6bd11a6e5822.png)

**Comment by jan-supernova** [comment]
Hey steveharman,
This is working as intended. *Use existing design* option means that your Navigation Bar will use the same design style (background colour, item colour, font etc.) as the previous Navigation Bar you have created. When you link your navigation bar this way and then change its attributes, it changes these attributes on all of the Screens on which it’s used in your project. You can think of it as shared styles. It is not supposed to have the same buttons or the same interaction functionality. 

Have a wonderful day!  
Jan, Supernova Team
