### ISSUE TITLE
Anomaly with Navigation Bar display

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#116]
### Issue
This is a non-functional UI-only issue with very low priority in my humble opinion.  ;-)

### Context
When navigating multiple screens in Edit mode only the screen that has focus renders the Navigation Bar component correctly.

### Observed in Supernova version
7.0 Beta 

### Current result
I have three screens, all of of which have a Navigation Bar component at the top. Two of the screens show the Navigation Bar as a white rectangle, only the foreground screen shows it correctly.

### Expected result
The two screens either side of the foreground screen should render the Navigation bar in the same way as the foreground screen does - not display white rectangles as they do now.

### Possible fix
Unknown.

### Screenshots
![Screenshot_28_05_2019__15_13](https://user-images.githubusercontent.com/12557929/58485084-44ee8480-815b-11e9-8599-663b78dd778f.png)

**Comment by steveharman** [comment]
**UPDATE:**  This is actually more of a functional issue after all.   

When the project is exported from Supernova to Xcode and deployed to a physical device, the Navigation Bar components are not rendered correctly - they appear as white rectangles.

![iPhone](https://user-images.githubusercontent.com/12557929/58555492-86416b80-8211-11e9-8ec4-fff3970fa1fc.png)

**Comment by jan-supernova** [comment]
Hey steveharman,  
We are happy to inform you that this issue with the Navigation Bar has been fixed in the latest version V7.7 of Supernova Studio. Thank you again for reporting this issue!

Have a wonderful day!  
Jan, Supernova Team
