### ISSUE TITLE
The "Screens" view ignores user's layout preference

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#117]
### Issue
This is another non-functional UI-only issue with very low priority in my humble opinion.  ;-)

### Context
I like to have the Screens on my "screen list" collapsed so the list is less cluttered and makes for easier viewing - the individual screen components are then hidden unless I expand any screen I'm interested in:

![Menubar_and_Viktory_iPhone8](https://user-images.githubusercontent.com/12557929/58485694-67cd6880-815c-11e9-9d45-4a49ac5bed51.png)

### Observed in Supernova version
7.0 Beta 

### Current result
If I navigate away from the "Screen list", for example by clicking on the Components list view, and then return to the Screens list view all the screens that I had previously collapsed are expanded.   

This is also true if I simply drag a screen up or down in the Screens list to re-order my screens even without navigating away.

![Menubar_and_Viktory_iPhone8](https://user-images.githubusercontent.com/12557929/58485809-a19e6f00-815c-11e9-8ec4-652908ba9be1.png)

### Expected result
The user's preferences for expanding some or all of their screens should be preserved.  Ideally as a global which persists across quitting & re-launching the same file in Studio, but at least when reordering Screens or clicking away & back again to the Screens list within the same session.

### Possible fix
Unknown.

### Screenshots
Please see above

**Comment by jan-supernova** [comment]
Hey steveharman,
     Thank you for your report. We have successfully simulated the issue in the latest version of Supernova Studio V7.2 and we are working hard on fixing it as soon as possible. We will inform you when your issue is resolved.

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey steveharman,
We are very happy to inform you that Screens are no longer ignoring your layout preference in the latest version V7.7 of Supernova Studio. Thank you again for reporting this issue!

Have a wonderful day!
Jan, Supernova Team
