### ISSUE TITLE
Undo operation is occasionally unavailable

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#118]
### Issue
When converting two or more labels into a Button component, the action cannot be undone

### Observed in Supernova Version
6.7 & 7.0 Beta 1

### Context

- My screen has two text labels; an "X" and the word "Cancel" next to it - both inside a view called "Exit" (an imported Sketch Group)
- I selected the group and used r/click > Convert to Component > Button
- This created a button with apparently only one item in it (the "X" icon)
- I tried to undo the action using Cmd-Z and the Edit menu.

### Expected result
Within reason, if a user can perform an action, they should be able to _undo_ an action

### Current result
Cmd-Z has no effect
Edit > Undo is greyed out

### Possible fix
Regular saving of the project file.  ;-)

### Screenshots
This is not 100% reproducible but the unavailability of Undo has happened to me on several occasions today - most recently as described above.  Usually, I close my Supernova project and revert to the saved copy to "undo" the change

**Comment by steveharman** [comment]
I managed to capture an "undo isn't available" case, this time it was converting an image view into a button component. After doing so the convert-to-button could not be undone.  

Video attached.

[supernovaUndo.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3231477/supernovaUndo.mp4.zip)

**Comment by jan-supernova** [comment]
Hey steveharman,
The issue with undo operation being occasionally unavailable had been fixed in the latest version of the Supernova Studio. Undo operation is working properly now after converting Label or Image View into a Button. Thank you again for reporting this issue!

Have a wonderful day!  
Jan, Supernova Team

**Comment by scheung38** [comment]
This is still the case with version V8.5 (build 12073) where I converted a View into a Button, but now I cannot Undo. Please help
