### ISSUE TITLE
Updated art board name not reflected in Screens list

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#119]
### Observed in Supernova version
6.7 & 7.0 Beta 1

### Issue
After changing the name of an artboard in Sketch, the new name isn't reflected in Supernova's list of Screens when the artboard is refreshed / re-imported.

### Context

- Import a Sketch file into a new Supernova project
- Rename one of the artboards in Sketch & save the file
- Use `Refresh` to re-import the artboard from the Sketch file into Supernova

### Expected result
The updated artboard name should be shown in Supernova's Screens list

### Current result
The artboard keeps its name from the original import and doesn't show the changes made.  

It is worth noting that the updated name **is** displayed correctly on the Refresh / Import file browser where the screens to be imported are selected, however, it isn't once the screen has been imported.

### Possible fix
Unknown

### Screenshots
![Menubar_and_Viktory_iPhone8_and_Viktory_iPhone8_copy_sketch](https://user-images.githubusercontent.com/12557929/58497300-9440af00-8173-11e9-84d5-8b7f41a60dbb.png)

**Comment by jan-supernova** [comment]
Hey steveharman,
This is working as best as it can right now. Supernova Studio currently does not know whether the user changed the Screen name after importing it or not. If we were to use the new Screen name from the refresh, the user could lose some changes they made inside the Studio, which we consider worse than not refreshing the Screen name. 
The solution would be to store the initial import values within the Supernova Studio. That way the Supernova Studio would know whether the initial values were changed by user or not. And if they weren't, it would update the unchanged values on refresh. However, this would have to work for all the attributes in the project and not just for the Screen name, so it will have to wait for now. However, we will keep this on our radar. Thank you for understanding.

Have a wonderful day!  
Jan, Supernova Team
