### ISSUE TITLE
Continually Crashes After Sketch Import

### ISSUE THREAD

**Issue by jimmyvfor3** [Supernova-Studio/public-issue-tracker#12]
See video. I'm unable to use the interface without it crashing after a sketch import. Currently running a el capitan 10.11.6
[errorVideo.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/1163852/errorVideo.mp4.zip)

### Issue
> 	[Provide general introduction to the issue]

### Context
> 	​[Provide more detailed introduction to the issue]

### Expected result
> 	​[describe what you would expect to happen]

### Current result
> 	​[describe what you currently experience]

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by JiriTrecak** [comment]
Would you mind re-testing with latest release (0.6.1) that we deployed today? Bonus: providing us with some design that you are testing on? Thank you! Your feedback helps a lot

sincerely,

Jiri

**Comment by jimmyvfor3** [comment]
Hi Jiri,

Thanks so much for the update. This seems to have fixed the issue. I'll
start playing with the interface and let you know what I think. In the mean
time have you thought about investing more in your Facebook page? I noticed
Anima did a great job with that and it led to some really good
community-driven ideas and it helped to build a loyal following. Just a
thought.

Best,
James



James Valladares
UX Designer, Build.com
www.jvalladares.com

**Comment by JiriTrecak** [comment]
@jimmyvfor3 definitely something that we are actively working on, now it has been crazy few days with the launch - would you mind dropping me a message on slack to discuss this little more? Curious :) 

Thank you for the feedback, closing

**Comment by jimmyvfor3** [comment]
​Sure thing, I will definitely do that. I do have a quick question though.
This is how the interface appears when I open the practice sketch file. The
design looks significantly different from the actual preview. Do you know
if this is a bug that needs to be worked out, or is it supposed to look
like this?​ As a designer with limited technical experience beyond
prototyping, I'm not sure.

Best,
James



James Valladares
UX Designer, Build.com
www.jvalladares.com

**Comment by JiriTrecak** [comment]
This is a bug known on 10.11, it does not happen on the 10.12. We will be trying to figure it out, it has something to do with the layout system. The initial idea was to only allow 10.12, but we went with 10.11 as well and.. yeah, we need to fix that :)

**Comment by JiriTrecak** [comment]
The preview should always reflect actual application, at least when you are in "interactive" mode.

**Comment by jimmyvfor3** [comment]
Ok I see. That makes sense, thank you. Let me know if you need any help
figuring out the bug. Looking forward to using the app once it's fixed.
Also another random thought, but it might be helpful to have a notification
when someone opens the application and an update is available.

Best,
James



James Valladares
UX Designer, Build.com
www.jvalladares.com

**Comment by jimmyvfor3** [comment]
Hey Jiri,

I just updated to the latest version, and they layout continues to be
messed up even in interactive mode. Do you by chance have an ETA for when
this bug will be fixed? I'd love to try out some of the features, but this
bug is still preventing me from doing so.

Thanks,
James



James Valladares
UX Designer, Build.com
www.jvalladares.com
