### ISSUE TITLE
Converting a view to button causes other components to disappear until the screen is refreshed

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#120]
### Issue
When converting a view to a button, other elements on the screen "disappear" until the screen is navigated away from and back to again (presumably redrawing it)

### Observed in Supernova version
6.7 & 7.0 Beta 2

### Context

- I have a view which I want to convert into a button component
- RightClick > Convert to component > Button

### Expected result
Converting a view to a button shouldn't affect other unconnected items on the screen

### Current result
Other elements on the screen "disappear"

### Possible fix

- Navigate away from the affected screen
- Navigate back to it
- The "disappeared" items are shown again

### Screenshots
Video attached in the .zip
[snsItemsDisappear.mp4.zip](https://github.com/Supernova-Studio/public-issue-tracker/files/3236604/snsItemsDisappear.mp4.zip)

**Comment by jan-supernova** [comment]
Hey steveharman,
Converting View into Button is no longer making other components disappear from the screen - components are redrawn immediately now. 

Have a wonderful day!  
Jan, Supernova Team
