### ISSUE TITLE
Supernova does not work properly with Style Overrides

### ISSUE THREAD

**Issue by libereducacao** [Supernova-Studio/public-issue-tracker#123]
### Issue
> 	When using style overrides in components, Supernova ignores them and use the default symbol style anyways.

### Context
> 	​Previously I was not using style overrides and the import to Supernova was working fine. Although, after starting to use the style override in my components, Supernova started to ignores the style defined by style override and uses the default style of the symbol instead.

### Expected result
> 	The components should not ignore the style override when imported to Supernova.

### Current result
> 	The components are ignoring the style override when imported to Supernova.

### Screenshots
> 	In Supernova: ![42e4eacf-7e9c-4eca-a68b-adb556762440](https://user-images.githubusercontent.com/50035156/59691371-4ee33080-91b9-11e9-8909-de64838b071c.jpeg)

> 	In Sketch: ![d2cbfec9-0098-4d11-85e9-0eb655fd5f89](https://user-images.githubusercontent.com/50035156/59691468-6c17ff00-91b9-11e9-9161-dd73713e7c8b.jpeg)

**Comment by jan-supernova** [comment]
Hey libereducacao,
     We would like to inform you that the issues with style overrides from Sketch had been fixed in the latest version of the Supernova Studio.

Have a wonderful day!  
Jan, Supernova Team
