### ISSUE TITLE
Action sheet not visible in Preview until refresh screen v6.10

### ISSUE THREAD

**Issue by AndyDentFree** [Supernova-Studio/public-issue-tracker#126]
### Issue
When adding Action Sheets to a button, cannot see them in Preview

### Context
- select a Button component
- change Interaction to _Show action sheet_
- enter a Title
- clear Message
- enter a Button Title

### Expected result
Going into Preview mode would allow me to click the button and see the Action sheet.

### Current result
Nothing happens in Preview when you click the button.

If you _refresh_ the preview by using the LHS navigator to go to a different screen them come back, the Action sheet displays as expected.

**Comment by jan-supernova** [comment]
Hey AndyDentFree,
     No matter how hard we tried, we have been unable to simulate the issue with the information provided. The Action Sheet was always visible in the Preview window for us no matter what we tried. We also used the same version of Supernova like you did - V6.10. It is possible that there is some small, but very crucial step that must be taken to properly simulate this issue. Could you provide us with the more information or better - a video? Your Mac can make a video of your screen by pressing Command + Shift + 5, selecting the region you want to record and then pressing Record. You can also contact me on Slack if you want - I am available there as well. Thank you very much for the answer.

Have a wonderful day!  
Jan, Supernova Team

**Comment by AndyDentFree** [comment]
I can't reproduce it either. 

I thought it might have been because I imported the screen with a refresh but that made no difference. It may have been something weird about my original document but that's a special legacy case that's been growing for multiple versions.

Will reopen if I reproduce it later whilst doing a few screens and make sure I am recording their addition but for now, it's not a bug.

**Comment by jan-supernova** [comment]
Hey AndyDentFree,
Thank you for the information. If you manage reproduce the issue in the future, do not hesitate to reopen this ticket and we will gladly help you.

Have a wonderful day!
Jan, Supernova Team
