### ISSUE TITLE
View jumps around between edit and preview

### ISSUE THREAD

**Issue by AndyDentFree** [Supernova-Studio/public-issue-tracker#131]
### Issue
There’s a disconcerting effect you can see in the [68MB movie](https://github.com/AndyDentFree/DDD19/blob/master/assets/menuAnimation.mp4) 

When you go into Preview mode, the vertical view jumps upwards. I just verified this is an issue with v6 as well so it’s not introduced in v7.

### Context
Sketch and snproject files were provided directly when giving some feedback on v7 animation but can be attached again.

I think the problem is related to having **non-standard artboard sizes**

### Expected result
More visual fidelity between Edit and Preview or, even better, detecting a design that is _bottom-oriented_ and creating the initial anchoring to match.

### Current result
Unless you go in and change the anchoring, just flipping between Edit/Preview has the menu as imported leap up and down.

![MenuAsImported](https://user-images.githubusercontent.com/1586093/62448265-f59b8480-b799-11e9-91c8-16121ca803bf.png)

![MenuInPreview](https://user-images.githubusercontent.com/1586093/62448271-fa603880-b799-11e9-94db-42b101ffb066.png)

**Comment by jan-supernova** [comment]
Hey AndyDentFree,  
Thank you very much for your report. Would it be possible to provide us with your Sketch and project files? You can send them to me on Slack as well. We will check your issue as soon as your files are available for us. Thank you very much.

Have a wonderful day!  
Jan, Supernova Team

**Comment by AndyDentFree** [comment]
Files are available on [github](https://github.com/AndyDentFree/DDD19/tree/master/menuAnimationDemo)

**Comment by jan-supernova** [comment]
Hey AndyDentFree,
Thank you for your Sketch and project files. We have been able to successfully simulate your reported issue in the latest version of Supernova Studio V7.2. We are working hard on fixing this issue as soon as possible. We will let you immediately know when the issue is resolved. Thank you again for your report.

Have a wonderful day!
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey AndyDentFree,
We have reviewed this ticket and we agree that the solution for this issue would be implementing a bottom-layout detector into Supernova Studio. However, this issue a big edge case for what we currently have to focus on. Thank you for understanding.

Have a wonderful day!
Jan, Supernova Team
