### ISSUE TITLE
It would be nice to have warning free XIB and Storyboard files on iOS export

### ISSUE THREAD

**Issue by relatedcode** [Supernova-Studio/public-issue-tracker#133]
<img width="1693" alt="warnings_storyboard" src="https://user-images.githubusercontent.com/5425762/62626566-f4985d80-b927-11e9-9bd4-e4ecb82044dd.png">

**Comment by relatedcode** [comment]
<img width="1468" alt="warnings_xib" src="https://user-images.githubusercontent.com/5425762/62626544-ea765f00-b927-11e9-846a-73721760cbe9.png">

**Comment by jan-supernova** [comment]
Hey relatedcode,
     Thank you for the report. We have been able to simulate the issue and we are aware of it. As Jiří told you on Slack, you can safely ignore the warnings for now - they are simply saying that constraints force the elements to have a bit different side than what is shown in Xcode itself. So while they are annoying, they are not an issue in the runtime. In the meantime, we will make sure that this issue is on our radar. We will inform you when this issue is fixed. 

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey relatedcode,
XCode uses different arithmetics and rules for the layout than we do. This means that unfortunately, some minor discrepancies will always occur. 

Have a wonderful day!
Jan, Supernova Team
