### ISSUE TITLE
IOS Simulator Not Working

### ISSUE THREAD

**Issue by morsamatias** [Supernova-Studio/public-issue-tracker#134]
### Issue
> 	When I try to run my project in the simulator its open the simulator but doesn't install my app. 

### Context
> 	​I have a MacBook Pro 2018 and the latest version of supernova.

### Expected result
> 	​Open the simulator with the app installed.

### Current result
> 	​Open the IOS Simulator but doesn't install the app.

### Screenshots

<img width="393" alt="Captura de Pantalla 2019-08-10 a la(s) 19 51 18" src="https://user-images.githubusercontent.com/33075003/62827602-831b1200-bba8-11e9-8024-ad51dd98cff4.png">
<img width="287" alt="Captura de Pantalla 2019-08-10 a la(s) 19 53 05" src="https://user-images.githubusercontent.com/33075003/62827607-86160280-bba8-11e9-9fdc-172b4029dbbf.png">
<img width="536" alt="Captura de Pantalla 2019-08-10 a la(s) 19 55 32" src="https://user-images.githubusercontent.com/33075003/62827622-e147f500-bba8-11e9-94c2-2a574ac681fe.png">

**Comment by jan-supernova** [comment]
Hey morsamatias!
     Thank you for your report. This issue is currently being in the process of fixing. It is also possible that this issue is caused by Xcode. So first of all, we recommend to try out these steps:

1. Try to make sure your simulators are working and communicating properly.
2. Try to reset iOS simulators by running `xcrun simctl erase all` command in the terminal.
3. Try to restart your computer - there might be some incorrectly ended service still running in the background that is interfering with the simulator and causing this issue.
4. Try to upgrade to the newest V7.0 version of Supernova and try to use the simulator in V7.0.

If none of the suggested steps helped with your issue, you can use a workaround to circumvent this issue; export the project in Supernova to iOS, then open and run it in Xcode directly.

Have a wonderful day!  
Jan, Supernova Team

**Comment by morsamatias** [comment]
I have tried exporting the project to Xcode and running the simulator there and it works. I have tried in the V7.0 version and y have done the first 3 steps that you recommend me and the problem still persists.

**Comment by jan-supernova** [comment]
Hey morsamatias,
We have just released the new version of Supernova Studio V8 in which we got rid of unreliable simulators altogether. As a replacement, we have completely redone the Preview mode - it can now work alongside your Edit mode, giving you constant 1:1 feedback as to whatever you are doing! And this is not everything - you can also detach the Preview from the Studio into the separate window and push it to your second monitor.

Have a wonderful day!  
Jan, Supernova Team
