### ISSUE TITLE
User interface is always in dark mode no matter what mode macOS is in

### ISSUE THREAD

**Issue by woolie** [Supernova-Studio/public-issue-tracker#139]
### Issue
> 	SuperNova Studio always seems to launch in dark mode, no matter mode is selected in macOS.

### Context
> 	​I use light mode.

### Expected result
> 	​I would expect that SuperNova Studio would switch to light mode for users in macOS light mode.

### Current result
> 	​Always in Dark Mode.

**Comment by JiriTrecak** [comment]
Hello @woolie,

Supernova's design doesn't depend on the Mac theme - we give users the option to force it, that is why it is not changing for you. Go to top menu > view > color scheme and pick one of the three options. Hope that helps!

**Comment by woolie** [comment]
That works for me.
