### ISSUE TITLE
Bundle Identifier doesn't stick

### ISSUE THREAD

**Issue by byteasc** [Supernova-Studio/public-issue-tracker#144]
### Issue
> 	Bundle Identifier doesn't properly update / save when set in Project Configuration

### Context
> 	Change project configuration to have a specific identifier. Go to Eport and it will have reset to default

### Expected result
> 	Identifier should be saved and kept on all screens

### Current result
> 	Identifier resets to io.supernova.spacebook

![image](https://user-images.githubusercontent.com/10793868/63896886-192ca600-c9b9-11e9-9390-2d22f5211d24.png)

**Comment by jan-supernova** [comment]
Hey byteasc,
     Thank you for your report! However, no matter how hard we tried, we have not been able to simulate the issue in the latest version of the Supernova Studio V7.3. Bundle identifier always stayed the same for us and never changed back to default no matter what we did. Could you please provide us with more information, or perhaps, with the video? It is possible to create a video on your Mac by pressing Command + Shift + 5. Thank you very much for your answer.

Have a wonderful day!  
Jan, Supernova Team

**Comment by byteasc** [comment]
Hey @jan-supernova , I will see what I can do and see if there is something in particular that seemed to cause it to default back and let you know

**Comment by byteasc** [comment]
Okay, after some fiddling, I cannot seem to get it to reproduce the exact same scenario but I did get it to act weird and maybe is the root for what I was seeing -

https://www.dropbox.com/s/x6bolq2l66e8il8/Screen%20Recording%202019-08-30%20at%2010.02.43%20AM.mov?dl=0

There seems to be issues with the UI tabs in Settings for the different types of Platforms as noticeable in my video. What the video exhibits may be what I was seeing and so I would replace the value thinking it wasn't saved, but in reality it was just displaying a different platform

**Comment by jan-supernova** [comment]
Hey byteasc,
This was probably the cause. However, we have made some significant changes under the hood of the Supernova Studio V7.7, which was released yesterday. We have not been able to simulate this issue in V7.7 anymore no matter how hard we tried. If you ever encounter this issue again, feel free to reopen this issue. Thank you again for your report. 

Have a wonderful day!
Jan, Supernova Team
