### ISSUE TITLE
Export to Flutter Have some issues

### ISSUE THREAD

**Issue by pazhut** [Supernova-Studio/public-issue-tracker#152]
i am using export to Flutter with the attached project.

i had observed few issues when running the project:

- on the ProfilePersonalnfo screen the camera button do not have the camera icon on it, to get to that screen click sign up on the main screen then sing up from the SignUp screen
-on the ConsumerJobs screen (click update on the ProfilePersonalInfo screen) you should observe some lines gets too long and exid the list cell boundaries

i am using SuperNova version 7.5 with Flutter 1.9 (latest)

i would attach the whole exported project but its very large

i hope this will be an easy fix

**Comment by jan-supernova** [comment]
Hey pazhut,  
Thank you for your report! We have been able to simulate the reported issue with the camera button not showing up in the Flutter export. We are not working hard to fix your issue as quickly as possible.
However, lines not matching the cell boundaries on ConsumerJobs Screen is not a Flutter related issue - your lines are not correctly set in your Supernova project. The easiest way to fix this is to select "bg" and "separator" views and check "Maintain horizontal content ratio" for them in the right menu. You can make sure they are correctly set by switching to Preview mode in Supernova Studio and changing the screen width.

Have a wonderful day!  
Jan, Supernova Team

**Comment by pazhut** [comment]
Hi Jan,

thanks for the information, i had tried following your recommendations but no luck, as you can see from the attached screenshots i had changed the setting of the components in SN Studio and its looks ok at the preview screen, but not when i export it and build it, you can see screens from both Android and IOS simulators, i hope you can help with this 

BR, Paz
<img width="1441" alt="Screen Shot 2019-09-17 at 5 21 25 PM" src="https://user-images.githubusercontent.com/55284761/65080797-1d246600-d970-11e9-8666-7e2ade7372eb.png">
<img width="1441" alt="Screen Shot 2019-09-17 at 5 21 37 PM" src="https://user-images.githubusercontent.com/55284761/65080811-244b7400-d970-11e9-8d40-57c1234b9e91.png">
<img width="1441" alt="Screen Shot 2019-09-17 at 5 21 45 PM" src="https://user-images.githubusercontent.com/55284761/65080817-28779180-d970-11e9-84e6-6cf1960596e1.png">
<img width="386" alt="Screen Shot 2019-09-17 at 5 16 39 PM" src="https://user-images.githubusercontent.com/55284761/65080823-2b728200-d970-11e9-8e46-eb66733b7fef.png">
<img width="448" alt="Screen Shot 2019-09-17 at 5 19 07 PM" src="https://user-images.githubusercontent.com/55284761/65080826-2d3c4580-d970-11e9-8dc1-1d2b27535c69.png">
