### ISSUE TITLE
missing identifier on iOS segue push calls

### ISSUE THREAD

**Issue by ward-at-hellotemp** [Supernova-Studio/public-issue-tracker#158]
### Issue
> 	[Provide general introduction to the issue]
Missing identifier in story board and calls for segue for iOS.
### Context
> 	​[Provide more detailed introduction to the issue]
No identifier is specified when creating segue push operations for iOS and subsequently calls to push the screens have empty strings for the segue identifier.  This means if two separate push calls are made that target different screens - typically 2 buttons - only one of those is ever accessible.
### Expected result
> 	​[describe what you would expect to happen]
One would expect the story board to be given an identifier such as UserLoginSeque, and calls like onMyButtonPressed the withIdentifer attribute would include "UserLoginSeque" instead of the empty string currently generated.
### Current result
> 	​[describe what you currently experience]
Only one seque per screen can be mapped without having to hand edit every seque in the story board and every Controller to make each seque code work.  If for some reason major changes to the supernova project needs to be made, any regeneration of code wipes out these changes.
### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]
Generate default identifiers for

### Screenshots
> 	​[if relevant, include a screenshot]

<img width="515" alt="Screen Shot 2019-10-18 at 3 03 29 PM" src="https://user-images.githubusercontent.com/54371084/67131186-876f3700-f1b8-11e9-8086-8efdd0ab51bd.png">

**Comment by jan-supernova** [comment]
Hey ward-at-hellotemp,
Thank you for your report. We have been able to simulate your issue in the latest version of the Supernova Studio V7.7. We are now working hard on fixing this issue as quickly as possible. We will let you know when your issue is resolved. Thank you again!

Have a wonderful day!  
Jan, Supernova Team

**Comment by morsamatias** [comment]
I got the same problem.

**Comment by jan-supernova** [comment]
Hey ward-at-hellotemp and morsamatias,
We are happy to let you know that we have just released a new version of the Supernova Studio V7.9 in which we addressed this issue. Segue identifiers are now properly exported to iOS platform in V7.9. Thank you again for reporting this issue to us!

Have a wonderful day!
Jan, Supernova Team
