### ISSUE TITLE
Screen Class Field is empty

### ISSUE THREAD

**Issue by ondevChrisD** [Supernova-Studio/public-issue-tracker#159]
### Issue
> 	Screen Class Field is empty, it used to auto populate according of page name 
Issue in latest V7.7 (Build 10491)

### Context
> 	​[Provide more detailed introduction to the issue]

### Expected result
> 	​[describe what you would expect to happen]

### Current result
> 	​[describe what you currently experience]

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​screenshot attached
<img width="1656" alt="Screenshot 2019-10-19 15 16 21" src="https://user-images.githubusercontent.com/8016255/67137602-d46c0f80-f283-11e9-836f-833b88a4cca7.png">

**Comment by jan-supernova** [comment]
Hey ondevChrisD,
Thank you for your report. We have been able to simulate this issue in the latest version of the Supernova Studio V7.7 and we are now working hard on fixing it as soon as possible with the high priority. In the meantime, you can set the Screen Class fields manually. 

Have a wonderful day!  
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey ondevChrisD,
We are happy to inform you that Screen Class fields are now properly generated after importing your design files into the latest version V7.8 of Supernova Studio, which is available right now. Thank you again for reporting this issue!

Have a wonderful day!
Jan, Supernova Team
