### ISSUE TITLE
Drop Shadow Imports to Xcode

### ISSUE THREAD

**Issue by JohnBHiggins** [Supernova-Studio/public-issue-tracker#16]
### Issue
Drop shadows do not import to Xcode.

**Comment by JiriTrecak** [comment]
<img width="1680" alt="gradients-shadows" src="https://user-images.githubusercontent.com/7470393/28792604-72b5c9c4-7630-11e7-9c32-45da58f3e40f.png">

Coming in 0.6.3 update for both iOS and Android
