### ISSUE TITLE
Studio (7.7) crashes when importing XD files

### ISSUE THREAD

**Issue by salmoro** [Supernova-Studio/public-issue-tracker#162]
### Issue
> 	Importing Xd files crashes Studio

### Context
> 	​This is my first time trying Supernova and it always crashes while trying to import any XD file.
 Versions: MacOs 10.13.6 SuperNova 7.7
Among some private files I was also able to reproduce this with the following public XD file:
https://www.xdguru.com/dark-mode-xd-login-signup-screens/

### Expected result
> 	Not to crash :)

### Current result
> 	​Crashes immediately after selecting file with no message or warning.

Very much looking forward seeing how this works and how it might be a game-changer in our development process. Thank you!

**Comment by jan-supernova** [comment]
Hey salmoro,
We are very sorry to hear that. We have tried to simulate the crashing issue with the public Sketch file you have included, but it opened in Supernova Studio V7.7 properly for us and didn’t crash even once. We have tried to delete Supernova Studio settings to simulate having fresh Supernova Studio, but the XD file opened properly for us as well. We have also tried other XD files we use for testing and they worked properly as well. Would it be possible to provide us with your other XD files that were causing your Studio to crash? If you are not comfortable sharing them here, you can send them to me on Slack. Thank you very much!

Have a wonderful day!  
Jan, Supernova Team

**Comment by salmoro** [comment]
@jan-supernova Thanks for responding.

I prefer avoiding sharing the personal files if we don't must as it entails a process on my end.

Is the fact that I've provided a public file which has the same results not good enough?

I can provider you with more (so far every XD file I've tried crashes the software). Or you can ask me to try specific files and I'll be happy to do so.

[This](https://ionic4themes.com/calendar/) public XD file is another example.

**Comment by jan-supernova** [comment]
Hey salmoro,
That is understandable. Thank you very much for providing us with another XD file. We are now currently investigating the possible cause more deeply since we were not able to simulate your issue manually - both XD files you have provided to us worked properly on our end and didn’t crash the Studio for us. We will let you know about the progress and our findings.

Have a wonderful day!
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey salmoro,
We have just released a new version of the Supernova Studio V7.9 with improved importing process that should address the issues you had. Can you let us know whether the import in V7.9 works correctly for you now? Thank you!

Have a wonderful day!
Jan, Supernova Team

**Comment by salmoro** [comment]
@jan-supernova Tried V7.9 and it's working well. Thank you!
