### ISSUE TITLE
studio v 7.8 still issues IOS in webview

### ISSUE THREAD

**Issue by vishwaprabhu** [Supernova-Studio/public-issue-tracker#163]
### Issue
> 	[ Still the webview fails to load on IOS simulator .Is there any alternate way to load a webview or local html file ]

**Comment by jan-supernova** [comment]
Hey vishwaprabhu,
Supernova Studio does not natively support local HTML files in the Web View component. However, it is possible for you to code your local HTML files into the project yourself - it should be a matter of the one line in the exported code. 

Have a wonderful day!  
Jan, Supernova Team

**Comment by vishwaprabhu** [comment]
Hey Jan,
Still webview not working .. please fix the same ASAP.
Have a great day..!
Prabhu TL
