### ISSUE TITLE
Update seems to have corrupted my supernova file

### ISSUE THREAD

**Issue by davearel** [Supernova-Studio/public-issue-tracker#167]
### Issue
I upgraded from `v7.6` to `v7.7` while I was working on a project in Supernova Studio. After updating, I closed out of the application and re-oppened only to find that my file no longer worked and it was throwing this error:

> "Supernova seems to have trouble opening your design. Please resave with the latest version of Supernova and try again (error: unpackingFailed(platform: Model.SCImportPlatform.supernova)).
>
> If this doesn't help, please help us improve your experience and send the file to support@supernova.io :)"

### Context
* Upgraded from `v7.6` to `v7.7`
* Project was set to use iOS' Swift 5, imported from Sketch.app

### Expected result
I expected to open my file without a hiccup.

### Current result
After "importing" for a while it shows this.
![Screenshot 2019-10-15 17 04 46](https://user-images.githubusercontent.com/1096881/68149943-6458bd00-ff04-11e9-8277-e6261f56350a.png)

### Possible fix
🤷‍♂ 

### Screenshots
> 	​See above

**Comment by jan-supernova** [comment]
Hey davearel,
Thank you very much for your report and for providing us with your project files via email. We have tried to open both of your project files in the newest version V7.9 of Supernova Studio and both projects opened properly for us. 
We have made some stability improvements regarding handling of projects in both V7.8 and V7.9 versions of Supernova Studio. So as a first step, we suggest to try to upgrade your Supernova Studio to the newest version and try to open your project files in it. If the issue still persists for you in V7.9 as well, let us know and we will take a deeper look at the possible cause of this issue for you. Thank you for letting us know!

Have a wonderful day!  
Jan, Supernova Team

**Comment by davearel** [comment]
Weird, I upgraded and it's still not working :( 

Is there some kind of cache or something that I can clear?

**Comment by jan-supernova** [comment]
Hey davearel,
You can try writing ``defaults delete com.supernova.studio`` into your terminal. In the case that doesn’t help, no worries, we will take a look at your file more closely and we will try to trigger this error through code on our side. 

Have a wonderful day!
Jan, Supernova Team

**Comment by davearel** [comment]
No luck, unfortunately. Let me know if you would like me to try anything else or have any questions. Thanks, Jan!

**Comment by jan-supernova** [comment]
Hey davearel,
We are sorry to hear that, but it was worth a try. We will investigate this issue in more depth and we will try to simulate your issue through code on our side. I will let you know about the progress and in the case of any additional questions. Thank you!

Have a wonderful day!
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey davearel,
We have just released the Supernova Studio V8, which came with improvements regarding of handling project files. We would like to ask you whether your project is opening properly for you in Supernova Studio V8 or not. Thank you very much for the answer!

Have a wonderful day!
Jan, Supernova Team

**Comment by jan-supernova** [comment]
Hey davearel,
Since the issue hasn’t been clarified for quite some time, we are closing this ticket. If you encounter this issue again or it still persists, feel free to reopen this ticket or to create a new one. Thank you.

Have a wonderful day!  
Jan, Supernova Team

**Comment by davearel** [comment]
I've moved on, but I wasn't able to open the file. Thanks for your help, though!
