### ISSUE TITLE
Cannot login using google account

### ISSUE THREAD

**Issue by cubissimo** [Supernova-Studio/public-issue-tracker#174]
### Issue
> 	Can't login using google accounts.

### Context
> 	Fresh install in lastest version, when trying to sign using google accounts provider.

### Expected result
> 	Get logged in in the app

### Current result
> 	​Receive a modal error with the following error:
JSON could not be serialized because of error:
The data couldn’t be read because it isn’t in the correct format.

### Screenshots
> 	
![image](https://user-images.githubusercontent.com/1638399/70176314-09f37d80-16b7-11ea-9a98-d2dc550a24df.png)

**Comment by jan-supernova** [comment]
Hey cubissimo,
Thank you for your report. This was the temporary issue caused by migrating and deploying our latest major release - V8. This is now resolved and works properly in the Supernova Studio V8.

Have a wonderful day!  
Jan, Supernova Team

**Comment by peddlem25** [comment]
I just had the same issue, still can't login.

**Comment by jeek600** [comment]
i have another login proplem , app wont open and wont login , Cause Of "server timeout"
