### ISSUE TITLE
Crash when change Progress View Color

### ISSUE THREAD

**Issue by ngocvu576** [Supernova-Studio/public-issue-tracker#175]
### Issue
> 	App go into crash

### Context
> 	​When I change color of progress view, app go into crash

### Screenshots
> 	​
<img width="304" alt="screen_shot_2019-12-05_at_18 19 06" src="https://user-images.githubusercontent.com/7045986/70292081-a4ff6b00-180f-11ea-9d24-183abd6ad907.png">

**Comment by jan-supernova** [comment]
Hey ngocvu576,
Thank you for your report! We have been able to simulate this issue in the latest version of Supernova Studio V8. We are now working hard on fixing your issue as quickly as possible. We will let you know when your issue is resolved. 

Have a wonderful day!  
Jan, Supernova Team
