### ISSUE TITLE
Fill Mode Toggle Disappear 

### ISSUE THREAD

**Issue by JohnBHiggins** [Supernova-Studio/public-issue-tracker#18]
### Issue
When you set a Fill Mode and then change which thing is being inspected in the right window then return to the element in which you changed the fill mode, the fill mode is blank.

**Comment by JiriTrecak** [comment]
That is for animations right? That means that property is not properly propagated to a model - will be fixed in the next release. Thanks

**Comment by JiriTrecak** [comment]
0.6.3 will fix this issue. Thank you for reporting it.
