### ISSUE TITLE
[iOS Export] LaunchImages causes build fail

### ISSUE THREAD

**Issue by nikitashekhov** [Supernova-Studio/public-issue-tracker#19]
### Issue
Example Project exported to iOS with generating resources at 2x and 3x fails because of inappropriate LaunchImages size.

### Context

- Xcode Version 8.3.3 (8E3004b), macOS Sierra 10.12.5, MacBook Air (13-inch, Early 2015)
- Supernova 0.6.2 (258)

### Possible fix
I manually fixed the sizes in Preview: made them 200% and build succeeded. 

### Screenshots
![screen shot 2017-07-26 at 11 10 36](https://user-images.githubusercontent.com/1727428/28611131-744e3d52-71f3-11e7-912f-b042a28255b7.png)

**Comment by JiriTrecak** [comment]
On non-retina screens, Supernova incorrectly exported images that are only half of the required size. 0.6.3 will fix this issue. Thanks for reporting it

**Comment by nikitashekhov** [comment]
👍
