### ISSUE TITLE
Fail to import sketch file

### ISSUE THREAD

**Issue by TakegawaPham** [Supernova-Studio/public-issue-tracker#201]
### Issue
> 	Can not import sketch file

### Context
> 	​The import button is gray

### Expected result
> 	​[describe what you would expect to happen]

### Current result
> 	​[describe what you currently experience]

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by jan-supernova** [comment]
Hey TakegawaPham!
We resolved this issue through the chat, so we are just letting you know that we are closing this ticket since it is no longer relevant. Have fun with Supernova Studio -- we’re super glad to have you on board!

Have a wonderful day!
Jan, Supernova Team
