### ISSUE TITLE
I what to cancel my subscription

### ISSUE THREAD

**Issue by AlexUpits** [Supernova-Studio/public-issue-tracker#204]
### Issue
> 	I don't find any link to access to cancel my payment.
I know it's not a bug, but I can't find another way to talk to you

**Comment by jan-supernova** [comment]
Hey!
If you want to cancel your subscription, then login to https://app.supernova.io/ with your Supernova account and change your Plan to a Free one following the steps in this article below:
**Changing or Deleting Your License** — https://supernova-helpdesk.crisp.help/en/article/changing-or-deleting-your-license-vaciiq/

Have a wonderful day!
Jan, Supernova Team
