### ISSUE TITLE
Error 404 Page Not Found (Download not available) 

### ISSUE THREAD

**Issue by infinZero** [Supernova-Studio/public-issue-tracker#207]
### Issue
> 	[404 Page not found]

[https://www.supernova.io/download](https://www.supernova.io/download)
That Page giving 404 Error page not found, as shown in attached

Actually I am an iOS Developer and now now learning Flutter, and 4 Days earlier I've watched Video tutorial of Supernova at YouTube, Since I am trying my best to download it but download page giving error and download link is not available, 

So will you please help me while suggesting from where to download it ?
Your Quick response will be highly appreciated.
Thanks
<img width="1440" alt="Screenshot 2020-12-28 at 12 59 25 PM" src="https://user-images.githubusercontent.com/14030777/103199803-80d86580-490d-11eb-868f-ace509a7d6d0.png">

**Comment by jan-supernova** [comment]
Hey infinZero!
Sorry for the late reply -- we were on holidays. :) Supernova Studio can be downloaded on our legacy website here -- https://legacy.supernova.io/download . Also, we love Flutter, so we decided to make Flutter platform in Supernova Studio completely free for all users, so you can keep using it with no limitations even if your trial expires. Enjoy!

Have a wonderful day!
Jan, Supernova Team

**Comment by infinZero** [comment]
Hello Jan, Supernova Team

Thanks for replying back, actually I was trying to download supernova
studio since 23 December and I thought it might be suspended by its vendors
due to some issues. Since I've watched its tutorial video at youtube, I
become its huge fan, hence I was willing to try this in my mac.
Thanks for letting me know that you've decided to make flutter platform in
supernova studio. Thats really awesome, please don't forget to upload its
tutorial videos too.
I am going to download it from your given link.
Once again. Thanks alot.
InfinZero
