### ISSUE TITLE
Sometimes crash

### ISSUE THREAD

**Issue by Pudge1996** [Supernova-Studio/public-issue-tracker#21]
I open the example file, and select "Username - email@example.com", and right click, select "Type -
 Text view" and crash, i must restart this software.

 Why I select Text view, and go crash? Maybe I do a  wrong operation?

**Comment by JiriTrecak** [comment]
Hey, we've discovered the primary cause behind this, and we will fix appropriately in the next version. Closing this issue when we release the update as we are tracking bugs internally.
