### ISSUE TITLE
[Android Export] Gradle Build fails due to unknown XML structure

### ISSUE THREAD

**Issue by ksbckr** [Supernova-Studio/public-issue-tracker#23]
### Issue
> 	The XML structure is not accepted by Android Studio.

### Context
> 	When exporting to an Android project, all the XML files have a <AEXMLDocument> tag surrounding the the content. 

### Expected result
> 	​After exporting for Android. The app should build without errors.

### Current result
> 	​I have to manually fix all XML files after Exporting

### Possible fix
> 	​<AEXMLDocument> should be removed from export I guess.

### Screenshots
>   <img width="1412" alt="bildschirmfoto 2017-08-01 um 09 32 00" src="https://user-images.githubusercontent.com/838419/28814060-4e8d52da-769c-11e7-95cb-b6516db0ec08.png">

**Comment by artufimtcev** [comment]
Will be fixed in 0.6.3

**Comment by artufimtcev** [comment]
Released in 0.6.3 as promised :)
