### ISSUE TITLE
ScrollView Horizontal View Gets Cut

### ISSUE THREAD

**Issue by rittim** [Supernova-Studio/public-issue-tracker#29]
### Issue
> 	[Horizontal size of ScrollView doesn't change and gets cut off even though it is pinned to the edges of the screen]

### Expected result
> 	​[Scroll view to hug the edges of the screen and not get cut off]

### Current result
> 	​[Scrollview gets cut off on larger screens]

**Comment by JiriTrecak** [comment]
Added to internal tracker [Supernova-Studio/supernova-studio-osx#173]
Expect the fix in the next release. Thank you.
