### ISSUE TITLE
Simulator not launching on some IDE configurations

### ISSUE THREAD

**Issue by JiriTrecak** [Supernova-Studio/public-issue-tracker#3]
### Issue
> 	When simulator is invoked through the studio, even if it is installed properly, it will not find the target to simulate (iOS) only 

### Current result
> 	We have disabled the simulators in latest build to reintroduce it when fixed

**Comment by pinotao** [comment]
so it will re-enabled at  0.7.0 milestone ?  0.7.0 means the next version ? how long it will take ...
