### ISSUE TITLE
Crash when trying to save after adding rotate-in animation

### ISSUE THREAD

**Issue by janninho** [Supernova-Studio/public-issue-tracker#45]
### Issue
> 	The app crashes when a rotate-in animation was added and then an attempt to save the file was made. Also, the file is corrupted afterwards and can't be opened anymore.

### Context
> 	​Running Supernova Studio on a MBP 9.2 with High Sierra. The crash is appears every time when following the above mentioned steps.

### Expected result
> 	​No crash and no corrupted file.

### Current result
> 	​Crash and corrupted file.

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by JiriTrecak** [comment]
Added to internal tracker [Supernova-Studio/supernova-studio-osx#170]
Expect the fix in the next release. Thank you.

**Comment by JiriTrecak** [comment]
Your issue has been fixed. It is scheduled for release with the next version. Thank you.
