### ISSUE TITLE
Preview mode isn't connected to zoom 

### ISSUE THREAD

**Issue by OskinPupin** [Supernova-Studio/public-issue-tracker#46]
### Screenshots
> 	​
<img width="1680" alt="snimek obrazovky 2017-10-09 v 18 48 22" src="https://user-images.githubusercontent.com/17280990/31349244-bf1ed6ce-ad22-11e7-9363-b30cfa11f9b3.png">

**Comment by JiriTrecak** [comment]
Added to internal tracker Supernova-Studio/supernova-studio-osx#160
