### ISSUE TITLE
Simulator Ios Isn't working 

### ISSUE THREAD

**Issue by franky2547** [Supernova-Studio/public-issue-tracker#48]
### Issue
> 	I tried to load up my app on a simulator. Whenever I click on simulator and Supernova opens up the simulator it just gets stuck on there.Whenever I click on simulator and Supernova opens up the simulator it just gets stuck on there.

 Expected Result
> 	I would expect when I click on simulator I could load up the app on a simulator

Current Result
> 	Whenever I click on simulator and Supernova opens up the simulator it just gets suck on there.

 Screenshots
> 
<img width="1440" alt="screen shot 2017-10-24 at 8 59 47 am" src="https://user-images.githubusercontent.com/14142257/31954301-151394a2-b89a-11e7-91cc-36f3e218a7e2.png">

**Comment by LordColus** [comment]
For me, whenever I try to launch the sim, Supernova crashes altogether.

**Comment by navsn** [comment]
Hi LordColus,

Check out our latest beta and let me know if it works for you. 

[Download the latest beta](https://api.supernova.studio/utils/download-beta)

Cheers,
Nav

**Comment by j0nscalet** [comment]
Hi @navsn-

I can confirm that the ios simulator works in version 0.9.9 (990), however it is not working for me in version 3.0.

Also, when I import my sketch design in 0.9.9 (990), images do not render properly. See: 
![image](https://user-images.githubusercontent.com/1328795/40273289-669eb7c2-5b72-11e8-8511-a2ed7dc2aced.png)

HTH!
