### ISSUE TITLE
Your DEMO project into Android Studio Run --> Error: Activity class {com.example.project/com.example.project.DiscoverVC} does not exist.

### ISSUE THREAD

**Issue by jorgefouto** [Supernova-Studio/public-issue-tracker#50]
1) Using your original DEMO, and then exported to Android Studio, at Run time, the following bug attached appeared.

2) Second bug...on your Studio, the icons seem corrupted.

<img width="1865" alt="androidrun_bug" src="https://user-images.githubusercontent.com/34586561/35332087-ac1db468-0101-11e8-9534-9fc5c2b22963.png">

<img width="2045" alt="studio_bug" src="https://user-images.githubusercontent.com/34586561/35332096-b0cf6d9e-0101-11e8-8b83-9ac4e44d9705.png">

**Comment by JiriTrecak** [comment]
Hey, thank you for reporting - we will look into it shortly. 

The second thing is not a bug - we are working on the new icon set and using visible placeholders so we don't forget to change anything.

**Comment by artufimtcev** [comment]
As for android exporter error, please try clean and rebuilding. Looks like your project was build successfully, so I'm pretty sure it should help. If that does't help, please send contents of your AndroidManifest.xml file and what activities you've got after export, thanks.
