### ISSUE TITLE
Image assets not exporting - rather big issue

### ISSUE THREAD

**Issue by PerfectedTech** [Supernova-Studio/public-issue-tracker#51]
### Issue
Assets do not export. All images are missing.

### Context
Doing export and/or upload to cloud project, image assets are missing.

### Expected result
There should be the image assets exported in the bundle.

### Current result
The assets are called on, but they are missing in the bundle. This happens in the cloud project view as well.

### Possible fix
Export the actual assets.

### Screenshots
![screen shot 2018-01-30 at 9 29 46 am](https://user-images.githubusercontent.com/1725606/35553334-2adc7d28-05a0-11e8-978b-322ac3833c07.png)
![screen shot 2018-01-30 at 9 29 35 am](https://user-images.githubusercontent.com/1725606/35553335-2b0ab116-05a0-11e8-81ba-f753f4576e53.png)

Here you can see the project has images in Supernova
![screen shot 2018-01-30 at 9 30 40 am](https://user-images.githubusercontent.com/1725606/35553370-5462c3fa-05a0-11e8-8023-9ded65626d3f.png)

**Comment by JiriTrecak** [comment]
Hey, thank you for reporting - would you mind sharing the design with us? This is something that we did not seen yet. You can send the link on jiri@supernova.studio - this would help us greatly (no worries, we get rid of the designs once they work).

Have a great day and sorry for the inconvenience,

sincerely

Jiri

**Comment by PerfectedTech** [comment]
Hi Jiri,
An email has been sent.
Thanks

**Comment by ALander26** [comment]
Was anything strange found? If I can help in any further way, please let me know.

**Comment by JiriTrecak** [comment]
Hey, we are currently working on resolving this issue - it is connected to more problems, so we are solving them all at once. Thank you for your patience, we'd like to have them solved by the end of the week.
