### ISSUE TITLE
Support Objective-C

### ISSUE THREAD

**Issue by jlubeck** [Supernova-Studio/public-issue-tracker#52]
I see that Swift, Android and React are supported. 

Any chance to support Objective-C as well?

**Comment by JiriTrecak** [comment]
Hey, it is currently a low priority for us - would you mind explaining the situation in which Obj-C would be beneficial to you? We see that most, if not all projects are started with Swift nowadays - and Obj-C pretty much serves as a legacy in projects that used it pre-swift. 

That being said, adding Obj-C support would be pretty easy with the current system, so more people are interested, the higher chance of us going for it.

**Comment by jlubeck** [comment]
On the company I work, most of the developers are still coding on ObjC and we reuse a lot of boilerplate code that is already in ObjC. Its not worth the time/money to switch to Swift, specially when it is still a language that keeps changing every year.

We also TRY not to use Swift libraries either, because as soon as you put that in a project, compile times skyrockets.

Of course I know ObjC is losing its share every single day, so I would understand if this is something you wouldn’t want to pursue as I’m not sure exactly how many customers it would give you.

It still looks like an awesome project!

**Comment by jlubeck** [comment]
Well thank you!

**Comment by jlubeck** [comment]
Well... ain't this a bummer...

**Comment by artufimtcev** [comment]
Hey @jlubeck 
Sorry that it didn't get into our priority list. As Apple moves further with Swift ObjC less and less popular among our users. As a startup, we have to prioritize our tasks and right now we cannot invest our time in this particular one. We're temporarily closing this one so people can know what we actually are working on with planning on reopening it once we get back to it.
