### ISSUE TITLE
github signup/login not working

### ISSUE THREAD

**Issue by catarino** [Supernova-Studio/public-issue-tracker#53]
### Issue
> 	github signup/login not working

### Context
> 	​when trying to signup, github signup window appears and it's possible to add auth details but after click Enter, process hangs as shown in attached image. If I click "Esc" it shows a popup with "The operation couldn’t be completed. (p2_OAuth2.OAuth2Error error 23.)" information.

### Expected result
> 	​login with github

### Current result
> 	​process hangs indefinitely. or it stops if one clicks "Esc" showing "The operation couldn’t be completed. (p2_OAuth2.OAuth2Error error 23.)"

### Possible fix
N/D

### Screenshots
![screen shot](https://user-images.githubusercontent.com/609172/37151310-de8f6530-22cc-11e8-90aa-6aadc980429e.png)

<img width="420" alt="screen shot 1" src="https://user-images.githubusercontent.com/609172/37151444-6b719838-22cd-11e8-8cc5-f5a85218f1e8.png">

**Comment by JiriTrecak** [comment]
Hello @catarino , we are aware of the issue - we'll be disabling it for launch and reenabling very soon, we just need to handle some things in our infrastructure first. Expect it within + - 2 weeks after launch on 03/13/18. Keeping the ticket open until we resolve it. Please use a different method of the login until then.

Sincerely,

Jiri, CEO, Supernova

**Comment by catarino** [comment]
ok! thx @JiriTrecak

**Comment by artufimtcev** [comment]
Github login will not be supported for now.
