### ISSUE TITLE
Main view collapsed

### ISSUE THREAD

**Issue by smallreflection** [Supernova-Studio/public-issue-tracker#55]
### Issue
> 	Was clicking around the interface and not quite sure what I did—somehow managed to collapse the main preview window, and only sidebars are showing. Can't quite figure how to get it back! Expanding to full screen simply shows sidebars centered in the view. Tried uninstalling and reinstalling but problem is persisting. This is on macOS High Sierra, 2017 MacBook Pro.

### Context
> 	​

### Expected result
> 	​I'd be able to see the design/preview interface. ;)

### Current result
> 	

### Possible fix
> 	

### Screenshots
> 	
<img width="462" alt="view_collapse_1" src="https://user-images.githubusercontent.com/8561791/37486883-37072858-2866-11e8-8f8f-d323593f3d21.png">
<img width="1440" alt="view_collapse_2" src="https://user-images.githubusercontent.com/8561791/37486884-3730ec88-2866-11e8-9198-031b0474324f.png">

**Comment by smallreflection** [comment]
Updated to 1.0.5 and I'm not getting any change here. Tried everything but no luck—is there a setting library file I can remove to try refreshing the view?

**Comment by artufimtcev** [comment]
UI has changed a lot since then, please reopen if still reproducible

**Comment by davearel** [comment]
This happened to me as well. I deleted ` /Users/[username]/Library/Preferences/com.supernova.studio.plist` which fixed the problem.
