### ISSUE TITLE
Can't find Xcode simulators

### ISSUE THREAD

**Issue by leachy14** [Supernova-Studio/public-issue-tracker#56]
### Issue
Currently have the latest version of Xcode and I can't run iOS simulator.

### Context
I am running beta High Sierra (10.13.2 (17C88))

### Expected result
I should be able to run the simulator but the button is grey.

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
![screen shot 2018-03-18 at 7 24 28 pm](https://user-images.githubusercontent.com/7918022/37572477-026dfa94-2ae2-11e8-9269-c4abae0ef3d9.png)

**Comment by manosteele91827** [comment]
Getting this same issue

**Comment by artufimtcev** [comment]
Simulators have been reworked since then, pls reopen if it's still an issue
