### ISSUE TITLE
Pin to edges - Views no longer stretching

### ISSUE THREAD

**Issue by Aaron-KSOC** [Supernova-Studio/public-issue-tracker#57]
### Issue
> 	Views have stopped stretching as they should.

### Context
> 	​Pinning a view to the edges no longer stretches a view as it should.  Happens on all view types.

### Expected result
> 	​The view should stretch when the resolution is different.

### Current result
> 	​The view does not stretch when the resolution is different.  This is on all screens and all views.  Occasionally it will stretch on some random view that I don't actually want it to.

### Possible fix
> 	​No idea really.  One thing I'm noticing is that I have a view with a bunch of card things in it.  When I try to click to pin the top of one and unpin the bottom, the one below it has it's top unpinned.  This behaviour was not previously present.

### Screenshots
> 	​
![editmode](https://user-images.githubusercontent.com/30246767/38591653-acd6ea1a-3d05-11e8-91c4-3c8b722e6847.png)
![previewmode](https://user-images.githubusercontent.com/30246767/38591660-bce317e4-3d05-11e8-9637-ed33c3e30f76.png)

**Comment by Aaron-KSOC** [comment]
Ok, doing some further troubleshooting I have found that if I create a new view it stretches properly.  Something has broken my already set up views.

**Comment by Aaron-KSOC** [comment]
Today it seems to be all working which sort of solves my problem, but I'd say the issue is still a thing so I'm not choosing to close the issue at this time.  I'll leave that up to you.

**Comment by Aaron-KSOC** [comment]
I would imagine this is the bug here.  This is a shot of the export in Android Studio.

![supernovaglitch1](https://user-images.githubusercontent.com/30246767/38709095-2fea8f24-3e87-11e8-8d89-c881e21f1f32.png)

**Comment by Aaron-KSOC** [comment]
I would imagine this is the bug here.  This is a shot of the export in Android Studio.

![Uploading supernovaGlitch1.png…]()

**Comment by Aaron-KSOC** [comment]
Reading the changelog for the update push today it would seem you have already fixed the bug shown in the last screenshot.  It doesn't seem to have fixed behaviour in Supernova Studio however.

**Comment by artufimtcev** [comment]
Layout has been reworked in the studio since then, pls reopen if it's still applicable
