### ISSUE TITLE
Unable to import Sketch design

### ISSUE THREAD

**Issue by gfhuertac** [Supernova-Studio/public-issue-tracker#60]
### Issue
> 	Today I updated Sketch to version 50 and Supernova Studio to 2.5, and now when importing a sketch design, all artwork (images, svg, etc) is not rendered in the Supernova-Studio 
> Until yesterday, with previous versions of Sketch and Supernova Studio, everything worked OK.

### Context
> 	Sketch version 50 and Supernova-Studio version 2.5

### Expected result
> 	The design should be imported properly and all the images should be available as resources

### Current result
> 	The design is imported but all the images are blank

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	Sketch App
![imagen](https://user-images.githubusercontent.com/598640/39840274-324116a6-53b5-11e8-8de3-8bb972b861b8.png)

> Supernova Studio import preview
![imagen](https://user-images.githubusercontent.com/598640/39840336-7b6b6dae-53b5-11e8-8c09-77465ac4f144.png)

> Imported design
![imagen](https://user-images.githubusercontent.com/598640/39840379-9bba6858-53b5-11e8-9d1f-8bcd291a9ebe.png)

**Comment by artufimtcev** [comment]
Should be fixed now, pls reopen if the issue still occurs and send us the sketch file if you can

**Comment by gfhuertac** [comment]
Yes, it is working. Thanks
