### ISSUE TITLE
Import Sketch File impossible

### ISSUE THREAD

**Issue by wortkotze** [Supernova-Studio/public-issue-tracker#62]
### Issue
Import of Sketch File not possible > Sketch File Version 50.2 / 55047

### Context
By importing the sketch file I receive the following bad behavior
![bildschirmfoto 2018-05-21 um 21 50 26](https://user-images.githubusercontent.com/1026043/40311021-3d9dd7b0-5d41-11e8-882a-24eddd7add37.png)

### Expected result
> 	​show screens as they are in sketch

### Current result
> 	​see screenshot

### Possible fix
> 	​I fixed It one time by reinstalling the software, but by the next import the problem came back

### Screenshots
> 	​see above

**Comment by ALander26** [comment]
Same as I think many people are reporting.

This is software I want to be able to use but right now is simply useless until this bug is fixed properly.

**Comment by JiriTrecak** [comment]
Hey guys, we are reviewing what is happening and will hopefully release fix soon. Thanks for your patience :)

**Comment by ALander26** [comment]
With all due respect, this issue might need priority. It has been present since before version 1.0...

**Comment by ALander26** [comment]
@JiriTrecak  Does 3.1 fix this issue?

**Comment by artufimtcev** [comment]
We are introducing new importer in the new version which should fix it, if you send us the sketch file we can make sure it won't be broken in the upcoming release

**Comment by PerfectedTech** [comment]
@JiriTrecak I could email you if you like.
