### ISSUE TITLE
Cloud sync: "403" User is not an Editor of the project

### ISSUE THREAD

**Issue by teamgroove** [Supernova-Studio/public-issue-tracker#63]
### Issue
Using "Cloud sync" with the Spacebook-example errors with the message: "403. user is not an editor on the project"

### Context
Supernova.studio -> cloud sync

### Expected result
sync to cloud

### Current result
errors with the message: "403. user is not an editor on the project"

### Possible fix
?

### Screenshots
![image](https://user-images.githubusercontent.com/2168067/40774185-3ea4e51e-64c5-11e8-960c-b7e9bf32cd8d.png)

**Comment by cpeople** [comment]
same error

**Comment by artufimtcev** [comment]
Uploading Spacebook was not allowed in V3, will be available in V4
