### ISSUE TITLE
Can't see the text in supernova studio

### ISSUE THREAD

**Issue by cpeople** [Supernova-Studio/public-issue-tracker#64]
### Issue
> 	Can't see the text

### Context
> 	​Can't see the text if even type is label

### Expected result
> 	​To show the text

### Current result
> 	​​Can't see the text if even type is label

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	
![2018-06-13 11 21 49](https://user-images.githubusercontent.com/27729151/41334011-56cdaca6-6efd-11e8-9841-6507f09f190d.png)

**Comment by artufimtcev** [comment]
Should be fixed now, pls reopen if it's still relevant
