### ISSUE TITLE
Not opening heavy sketch files

### ISSUE THREAD

**Issue by charanuxd** [Supernova-Studio/public-issue-tracker#65]
### Issue
> 	[Supernova is not opening one of my sketch files that's 43mb of size]

### Context
> 	​[I think it doesn't support heavy sketch files]

### Expected result
> 	​[It should open those heavy sketch files too]

### Current result
> 	​[Currently it's not]
![screen shot 2018-06-22 at 3 02 04 pm](https://user-images.githubusercontent.com/30448568/41769537-3ec9944e-762d-11e8-8fa4-82d1bb7c0723.png)

### Screenshots
> 	​[Currently it shows only a blank screen when I import my sketch file]

**Comment by artufimtcev** [comment]
We are reworking sketch importer for V4, please send me the sketch file to artem@supernova.studio and we'll make sure it's 100% working in the next verion
