### ISSUE TITLE
Few layers are displayed wrong in the active view ( simulator )

### ISSUE THREAD

**Issue by markovicvojo** [Supernova-Studio/public-issue-tracker#66]
### Issue
> 	[
A few layers are changed in the active view or in the simulator. Especially shapes like circles or rounded rectangles]

### Screenshots
> 	​[
<img width="1280" alt="bildschirmfoto 2018-07-06 um 18 54 39" src="https://user-images.githubusercontent.com/40897605/42391638-54a855f6-8150-11e8-8a16-adf782dbb195.png">
![Uploading Bildschirmfoto 2018-07-06 um 18.54.23.png…]()
![Uploading Bildschirmfoto 2018-07-06 um 18.54.56.png…]()

]

**Comment by artufimtcev** [comment]
That's correct, Merge as image should do the trick
