### ISSUE TITLE
fontFamily 'Lato-Regular' is not a system font and has not been loaded through Expo.Font.loadAsync. 

### ISSUE THREAD

**Issue by ArronHsiao** [Supernova-Studio/public-issue-tracker#68]
### Issue
Hi, I'm using Supernova's build in example -Spacebook to export to React Native project,
and when I do $npm start, the fontFamily 'Lato-Regular' error occurs, can't find this font from code.

**Comment by ArronHsiao** [comment]
I think I solve the problem by rename the file name:  './Assets/fonts/Lato 300.ttf'  to the filenames without space :  './Assets/fonts/Lato300.ttf' , and Expo simulation runs well. But I still think this is a bug for exporting to React Native for the fonts filename, hope this can be solved in the next version.

**Comment by JiriTrecak** [comment]
Hello, this problem is resolved in the next version of Supernova, V4. It is our biggest update yet and if you want, I'd like to invite you to beta https://supernova.studio/download-beta - it will be worth it, we promise :)
