### ISSUE TITLE
right side bar is pink

### ISSUE THREAD

**Issue by kdsaft** [Supernova-Studio/public-issue-tracker#69]
### Issue
> 	[Provide general introduction to the issue]

### Context
> 	​[Provide more detailed introduction to the issue]

### Expected result
> 	​[describe what you would expect to happen]

### Current result
> 	​[describe what you currently experience]

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by kdsaft** [comment]
In either the light or dark theme, the right sidebar is pink...
<img width="231" alt="screenshot 2018-08-09 13 34 17" src="https://user-images.githubusercontent.com/15327270/43896479-44298bca-9bd9-11e8-9488-7ffb9b805028.png">
<img width="224" alt="screenshot 2018-08-09 13 36 17" src="https://user-images.githubusercontent.com/15327270/43896480-444c4e6c-9bd9-11e8-920b-7ed79c64c6aa.png">

**Comment by JiriTrecak** [comment]
Hello, thanks for reporting. This is due to beta of 10.14. We haven't yet allocated resources to it, but we'll fix it soon. Will inform you!
