### ISSUE TITLE
Nav View CTRL-Z Does not Work

### ISSUE THREAD

**Issue by berenerchamion** [Supernova-Studio/public-issue-tracker#7]
### Issue
> 	If I move a screen in the navigation view and then hit CTRL-Z it does not go back to the original location. 

### Context
> 	​[Provide more detailed introduction to the issue]

### Expected result
> 	CTRL-Z would undo the change. 

### Current result
> 	​Nothing happens when you hit CTRL-Z.

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

### Screenshots
> 	​[if relevant, include a screenshot]

**Comment by JiriTrecak** [comment]
Will be resolved in the next update. Thank you :)

**Comment by JiriTrecak** [comment]
Added to internal tracker [Supernova-Studio/supernova-studio-osx#172]
Expect the fix in the next release. Thank you.
