### ISSUE TITLE
Supernova Studio closes when trying to export to Android

### ISSUE THREAD

**Issue by lucasharada** [Supernova-Studio/public-issue-tracker#72]
### Issue
> 	I imported a project from Sketch, added some interactions on the elements and exported to iOS. Everything went smooth. When trying to export to Android, the application closes without showing any error.

### Context
> 	When Export to Android option is selected, a dialog showing "Preparing project export" appears and the Supernova Studio closes right after.

### Expected result
> 	Show an error message or complete the export successfully.

### Current result
> 	Supernova Studio closes without any feedback.

**Comment by artufimtcev** [comment]
Hey, could you please provide us with the project file that is crashing? I cannot see any Android related crash in our logs. You can send it to me to artem@supernova.io
