### ISSUE TITLE
Interface collapsed to sidebar only

### ISSUE THREAD

**Issue by smallreflection** [Supernova-Studio/public-issue-tracker#77]
### Issue
> 	UI is collapsed to only the (apparently) sidebar pane and a few top options. 

### Context
> 	​Whenever I attempt to open the app.

### Expected result
> 	To see the full UI. 😄 

### Current result
> 	​When I open the app only the sidebar appears with its tabs. This happened in an earlier beta and even after downloading newer releases it persists, and I can't find any setting or menu command to make the rest of the UI display again. Any help or a setting file I can delete to reset?

### Possible fix
> 	​

### Screenshots
> 	​
<img width="398" alt="supernova_collapsed_issue" src="https://user-images.githubusercontent.com/8561791/47753002-81f9a380-dc6c-11e8-8a03-d65ae093c2d5.png">

**Comment by JiriTrecak** [comment]
Please follow these steps to fix it:
- Quit Supernova
- Open terminal
- Type `defaults delete com.supernova.studio`
- Reopen Supernova

If it doesn't help, delete and reinstall Supernova. We are investigating the root cause. Thank you very much for your bug report.

**Comment by smallreflection** [comment]
Thanks @JiriTrecak! Worked like a charm. 😃
