### ISSUE TITLE
iOS generated launch images are not correct

### ISSUE THREAD

**Issue by schayes04** [Supernova-Studio/public-issue-tracker#8]
### Issue
When you export any project to Xcode, the launch images are not the correct size. Xcode throws an error and won't let you run the project.

### Context
Xcode 8.3.3, macOS Sierra 10.12.6

### Expected result
Correct dimension launch images or a launch image storyboard file

### Current result
Incorrect dimension launch images

<img width="258" alt="screen shot 2017-07-19 at 2 59 31 pm" src="https://user-images.githubusercontent.com/4382161/28385059-b8209d4a-6c94-11e7-9750-080aad9f02a4.png">

**Comment by JiriTrecak** [comment]
Will be resolved in the next update. Thank you :)
