### ISSUE TITLE
Elements disappearing upon importing Sketch design

### ISSUE THREAD

**Issue by niclaflair** [Supernova-Studio/public-issue-tracker#80]
### Issue
> 	Elements disappearing upon importing Sketch design

### Context
> 	I've read Supernova 101: Preparing Designs and prepared my design accordingly. Once I import my design from Sketch some of the elements in the design turn up missing. Also, when I converted an element to a Button it just disappeared. I switched it back to View but it still remained unseen.

### Expected result
> 	As a designer, to be able to import your designs and have them properly converted to code is a godsend. Saves a lot of time and money. - IMO Supernova Studio would kill its competition if it emphasized: "skip hiring a frontend dev" and catered more to just designers instead of designers who also code.

### Current result
> 	I would like to purchase and subscribe to the CODE plan but unfortunately, I won't be doing that because my designs will not import properly. 

### Screenshots
> 	
![screen shot 2019-01-19 at 6 18 32 pm](https://user-images.githubusercontent.com/46303225/51434127-33c6c180-1c17-11e9-9113-b5801b60304d.png)
![screen shot 2019-01-19 at 6 20 07 pm](https://user-images.githubusercontent.com/46303225/51434128-36291b80-1c17-11e9-97d3-fa33964c17ee.png)

**Comment by artufimtcev** [comment]
Hey, thanks for reporting, we are preparing our own renderer (sketch-independent) with V6 which will fix those issues. You will get extra trial time so you can test it more once it's fixed

**Comment by JiriTrecak** [comment]
Fixed in V6
