### ISSUE TITLE
Refresh should preserve local edits

### ISSUE THREAD

**Issue by AndyDentFree** [Supernova-Studio/public-issue-tracker#81]
### Issue
Refreshing the design from a Sketch artboard currently completely re-imports the screen, wiping out all changes, even if only trivia.

### Context
- Create a new SNS document from scratch by importing a Sketch document
- Edit a screen in the SNS document, assigning component types such as Button.
- Add animations to the screen
- Refresh by choosing that artboard in the Refresh picker

### Expected result
- Elements in the Sketch design which were unchanged will not be affected.
- Elements changed to components will remain as components and visual property changes such as position, colour etc be propagated if they had changed in Sketch
- Localisations will be preserved

### Current result
The screen is completely re-imported, deleting the existing, even if the Sketch design has not changed at all. Localisations are also dumped.

### Possible fix
Without knowing anything about the internals of Supernova Studio, considering a _diff approach_ like the reconciliation of models with the DOM in React and Elm, compare the import with the previous import to build up a list of delta operations to apply to change the refreshed page.

If there is too much change, give the user the option to reimport from scratch.

Alternatively, saving all the operations applied by the user to an imported model, import from scratch then re-apply the known operations. (That implies recording operations that coalesce elements such as setting a view with nested items to a Navigation bar, and recording deletions).

**Comment by JiriTrecak** [comment]
Implemented in V6
