### ISSUE TITLE
Font Awesome Icon Fonts not being rendered correctly

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#82]
- macOS 10.14
- Supernova 5.5
- Sketch 52.5

### Issue
Like many people we use Font Awesome Pro 5  ('FA') icon fonts in our designs, but they don't seem to play nicely with Supernova.  

### Context

1. - Create a screen in Sketch
2. - Add a text layer
3. - Specify Font Awesome Pro 5 as the font and choose an icon (any)
4. - Save the file / artboard and import it  into Supernova

### Expected result
Supernova should display the FA icons as they are in positioned in Sketch

### Current result

- Case: A Sketch artboard called "Logo" contains a simple group made up of an oval layer and an FA text layer.
- Supernova shows information about the "Logo" group such as the layer's name and the FA icon's component type=text, but the oval & FA icon _are not displayed_ in Edit or Preview mode within Supernova.

### Screenshots

- The attached screenshot shows the correct layout in Sketch (on the left) and how Supernova renders it (on the right).  
- The two elements that Supernova renders correctly are shapes imported as SVGs and are _not FA icons_.  
- The three elements _missing_ in Supernova are the FA icons themselves and the oval layers they were positioned on.

![login_sketch](https://user-images.githubusercontent.com/12557929/52227630-f9605400-28a7-11e9-8b8b-8aa92b2c57e2.jpg)

**Comment by JiriTrecak** [comment]
Implemented in V6
