### ISSUE TITLE
Unable to read Supernova plugin labels in Dark Mode

### ISSUE THREAD

**Issue by steveharman** [Supernova-Studio/public-issue-tracker#83]
- macOS 10.14
- Supernova 5.5
- Sketch 52.5

### Issue
When using the Mac in Mojave's "Dark Mode" it isn't very easy to read the Supernova plugin labels in Sketch.

### Screenshots
![plugin](https://user-images.githubusercontent.com/12557929/52227811-7f7c9a80-28a8-11e9-82bd-71b47405e04d.jpg)

**Comment by jan-supernova** [comment]
Hey steveharman,
We got rid of the Sketch plugin in the latest version of the Supernova Studio V8 as it no longer served any purpose. Supernova Studio can import and work with native Sketch designs with no plugins necessary.

Have a wonderful day!  
Jan, Supernova Team
