### ISSUE TITLE
Setting component to Segmented Control sorts titles

### ISSUE THREAD

**Issue by AndyDentFree** [Supernova-Studio/public-issue-tracker#86]
### Issue
> 	Converting a component to a Segmented Control sorts the titles

### Context
- Created a page in Sketch with a Segmented Control using Apple's symbols, first item "Text" second item "Envelope"
- Imported page to create new Supernova document - appeared OK
- Used the context menu to convert the component to Segmented - titles appeared sorted.

### Expected result
> 	The group becomes a Segmented Control looking nearly identical to the Sketch original.

### Current result
> 	A Segmented Control is created but the titles are sorted alphabetically.

### Possible fix
> 	​[not obligatory, but suggest fixes or reasons for the bug]

Supernova Studio v5.7 (build 3910)

**Comment by jan-supernova** [comment]
Hey AndyDentFree,
Converting a group with components to Segmented Control now sorts components to match the way how they are placed in the Components menu, not alphabetically. Please let us know if you have any further issues with Segmented Control. Thank you!

Have a wonderful day!
Jan, Supernova Team
