### ISSUE TITLE
Refresh Duplicates Resources

### ISSUE THREAD

**Issue by bigmountainstudio** [Supernova-Studio/public-issue-tracker#89]
### Issue
> 	When refreshing, resources are getting duplicated and older versions of changed resources are persisting

### Context
> 	If you import a simple Sketch file with a square, you will see one square resource. Then if you refresh and re-import the same Sketch file, a duplicate square resource appears.

### Expected result
> 	Resources should not duplicate. And if you change a resource, the old one should not persist.

### Current result
> 	Every time you refresh, a new resource is created.

### Possible fix
> 	Maybe associate resources with artboards and if an artboard is refreshed, all previous resources relating to that artboard are removed and new resources are created?

### Screenshots
> 	
<img width="1392" alt="5-Old images" src="https://user-images.githubusercontent.com/24855856/54096917-8862ff00-4373-11e9-8abc-635ea31fb906.png">

**Comment by JiriTrecak** [comment]
Fixed in V6
