### ISSUE TITLE
Not recognizing flutter environment

### ISSUE THREAD

**Issue by pruales** [Supernova-Studio/public-issue-tracker#91]
### Issue

I'm using Supernova v6 and trying to export my project to Flutter v1.2.1. However, Supernova keeps displaying the dialog asking to setup Flutter environment before exporting.
### Context

I just have a simple login screen that I want to test in Flutter but the export to Flutter wont work. My Flutter environment isn't being recognized.
### Expected result

I would expect my project to be exported since I have a Flutter environment setup.
### Current result

No export to Flutter.
### Possible fix

I'm not sure what Flutter requirements you guys have.

### Screenshots
<img width="564" alt="Screen Shot 2019-03-11 at 1 48 15 AM" src="https://user-images.githubusercontent.com/21148863/54102669-c83fdb80-439f-11e9-95cd-56d8bfb9c1cf.png">

![Screen Shot 2019-03-11 at 1 48 04 AM](https://user-images.githubusercontent.com/21148863/54102734-063cff80-43a0-11e9-8aeb-1d4ce446da1d.png)

**Comment by ndrd** [comment]
Same issue here! 

![Screenshot 2019-03-14 at 10 09 42 AM](https://user-images.githubusercontent.com/8826286/54372640-54bcf900-4641-11e9-8ca6-a0c542e470d8.png)

**Comment by artufimtcev** [comment]
Thanks for reporting! We'll address this issue asap. Drop me an email at artem@supernova.io with your Supernova account's email and we'll extend trial for you.

**Comment by andreahaku** [comment]
Same thing for me as well.
Flutter is installed and working as I work with it every day.
But it's not recognised.

**Comment by artufimtcev** [comment]
In addition to the things mentioned in the error message please make sure Flutter is permanently added to `.bash_profile` file as described [here](https://flutter.dev/docs/get-started/install/macos#update-your-path). They do not have it included in the main setup flow, but Supernova requires access to it with clean terminal session

**Comment by andreahaku** [comment]
Thanks that solved. Unfortunately not everyone uses Bash as the default shell ;) I don't.

**Comment by artufimtcev** [comment]
Yeah, there are several weak spots in generating flutter projects with CLI tool. Currently we are working on our own project generator that will not depend on the CLI and flutter environment, so such problems won't be encountered in future versions at all.
