### ISSUE TITLE
[react native] untouchable buttons and unfillable input text

### ISSUE THREAD

**Issue by wasa4587** [Supernova-Studio/public-issue-tracker#92]
### Issue
When I export the project to react native, It creates a lot of Views with an absolute position with 100% * 100% size, which covers all components and makes them uninteractive, I can't press buttons nor filling input text, so on...

### Context
Supernova V6.0
Mac Mojave 10.14.3

In all screens, I can find some View with 100% * 100% absolute position.
The preview in supernova app I'm able to press the buttons, and the transition works well.
When I export the app to react native, these View's are covering all the screen or big areas.
These View's are over all the elements including buttons.
It makes buttons untouchable, input text unfillable, so on...
I checked sketch design and there isn't anything grouping or wrapping the whole screen.
```
        <View
          style={{
            width: "100%",
            height: "100%",
            position: "absolute",
          }}>

```

### Expected result
 	The exported code works the same than preview in supernova.

### Current result
       I can't interact with the components, press buttons nor fill input text fields, switch switches, so on..
       because there is a transparent View over all the screen, or covering big areas     

### Screenshots

Sketch design
<img width="310" alt="Screen Shot 2019-03-11 at 9 35 20 AM" src="https://user-images.githubusercontent.com/2035706/54136248-03aeca00-43e1-11e9-93d4-674d4c09255d.png">
<img width="232" alt="Screen Shot 2019-03-11 at 9 35 15 AM" src="https://user-images.githubusercontent.com/2035706/54136259-0ad5d800-43e1-11e9-8e8e-d8925d7ecdd0.png">

Using the inspector to see the transparent View covering all the screen
<img width="393" alt="Screen Shot 2019-03-10 at 4 02 20 PM" src="https://user-images.githubusercontent.com/2035706/54135528-977f9680-43df-11e9-864f-fc695756a9c2.png">

The generated code by supernova
<img width="449" alt="Screen Shot 2019-03-10 at 4 02 38 PM" src="https://user-images.githubusercontent.com/2035706/54135526-96e70000-43df-11e9-885b-e34a3d074a95.png">

supernova and sketch components, they are not wrapped
<img width="304" alt="Screen Shot 2019-03-10 at 4 03 34 PM" src="https://user-images.githubusercontent.com/2035706/54135534-98b0c380-43df-11e9-8e0b-c99fb95fa98c.png">
<img width="225" alt="Screen Shot 2019-03-11 at 9 26 13 AM" src="https://user-images.githubusercontent.com/2035706/54135629-c39b1780-43df-11e9-90ea-aa03716f1c39.png">

**Comment by artufimtcev** [comment]
We'll add `pointerEvents="box-none"` to the generated containers so it doesn't consume events in the next version, you can do the same thing in code so you are not blocked on with in the meanwhile 
Example:
```
        <View
          pointerEvents="box-none"
          style={{
            width: "100%",
            height: "100%",
            position: "absolute",
          }}>
```

**Comment by artufimtcev** [comment]
Should be fixed now.
