### ISSUE TITLE
Supernova V6.0 crashes

### ISSUE THREAD

**Issue by wasa4587** [Supernova-Studio/public-issue-tracker#94]
### Issue
I was working on transitions or converting View's into Input text or buttons and it suddenly crashes
It crashes 3 times in 8 hours
### Context
Supernova V6.0
Mac Mojave 10.14.3

It's common that supernova freezes sometimes, I imagine because of the number of screens,
but sometimes it crashes after freezing

### Expected result
It doesn't crash

### Current result
It's crashing, The app is suddenly closed

**Comment by artufimtcev** [comment]
Could you send me an example Supernova project save file where we can replicate this crash? Provided it's still an issue in 6.1 of course

**Comment by JiriTrecak** [comment]
Fixed in V6.x
