### ISSUE TITLE
styles are getting broken when converting to a Flat list

### ISSUE THREAD

**Issue by wasa4587** [Supernova-Studio/public-issue-tracker#95]
### Issue
I have a list of components, then I convert the component that is grouping them into a Flat list and the styles are broken

### Context
Supernova V6.0
Mac Mojave 10.14.3

### Expected result
The components keeps the styles

### Current result
The styles are broken

### Possible fix
Maybe using ScrollView, or adding another option that uses it

### Screenshots
before
<img width="410" alt="Screen Shot 2019-03-11 at 10 10 11 AM" src="https://user-images.githubusercontent.com/2035706/54139059-53dc5b00-43e6-11e9-8721-8ce58b731602.png">

after
<img width="422" alt="Screen Shot 2019-03-11 at 10 10 25 AM" src="https://user-images.githubusercontent.com/2035706/54139051-4fb03d80-43e6-11e9-873d-bb00160afb43.png">

**Comment by artufimtcev** [comment]
In case of FlatList in Supernova, you'd have to embed the spacing into the cell. You can create a cell and position the white rectangle and it's content inside the cell. Let me know if you need further clarifications!
