### ISSUE TITLE
Flutter doesn't generate any code at all for me.

### ISSUE THREAD

**Issue by neiljaywarner** [Supernova-Studio/public-issue-tracker#97]
### Issue
No generated dart source code at all for Flutter

### Context
Screens blank in the source code view
### Expected result
> 	​[describe what you would expect to happen]

### Current result
> 	blank screen on the code side.

Just downloaded supernova 15-march-2019

**Comment by artufimtcev** [comment]
Could you try v6.2? If it still happens, please send us project save file to support@supernova.io, we will fix it asap, thank you!
